version: '3.5'
services:
  dropbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dropbox  
    environment:
      UID: $myuid
      GID: $mygid
    volumes:
      - $PWD/app/config:/dbox/.dropbox
      - $PWD/app/drive:/dbox/Dropbox
    hostname: $myhostname