version: '3.5'
services:
  dbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dropbox  
    environment:
      UID: $myuid
      GID: $mygid
      TZ: $mytimezone  
    volumes:
      - $PWD/app/config:/dbox/.dropbox
      - $PWD/app/drive:/dbox/Dropbox
    hostname: $myhostname